AndrosovichProj/src/test/java/mainPack/AppTest.java
AndrosovichProj/src/test/java/mainPack/test

Androsovich 12 07

---

TabelProj/src/test/java/mainPack/AppTest.java

Tabel 12.07.2018

---

PetrovskaiaProj/src/test/java/mainPack/AppTest.java

Petrovskaia12-07

---

VoloschukProj/src/test/java/mainPack/AppTest.java

Voloshchuk 1207

---

MaruschakProj/src/test/java/mainPack/AppTest.java

Marushchak 12 07

---

PasternakProj/src/test/java/mainPack/AppTest.java

Pasternak 12 07

---

MatiushinProj/src/main/java/mainPack/App.java
MatiushinProj/src/test/java/mainPack/AppTest.java

Matiushyn 1207

---

GnatiukProj/src/test/java/mainPack/AppTest.java

Gnatiuk12.07

---

BychovyiProj/src/test/java/mainPack/AppTest.java

Bychovyi 12 07

---

KushnirProj/src/test/java/mainPack/AppTest.java

Kushnir 12.07

---

KurishkoProj/src/test/java/mainPack/AppTest.java

Kurishko 16 07

---

GnatiukProj/src/test/java/mainPack/AppTest.java
GnatiukProj/src/test/java/mainPack/TestCases

Gnatiuk 17 07

---

KushnirProj/src/test/java/mainPack/TestSuit_1

[QA] Test suit was added

---

MatiushinProj/src/test/Test_cases_plagiary.txt
MatiushinProj/src/test/UIMapping.properties

locator-homework

---

KushnirProj/src/test/java/mainPack/UiMaping.properties

Kushnir 24.07

---

GnatiukProj/src/main/java/mainPack/TestCases_and_Locators
GnatiukProj/src/test/java/mainPack/TestCases_and_Locators

Gnatiuk hw 22.07.18

---

KushnirProj/pom.xml
KushnirProj/src/test/java/loginTests/LoginTestWithOutPageObject.java

[QA] loginTestWithOutPageObject

---

MatiushinProj/pom.xml
MatiushinProj/src/test/java/loginTests/LoginTestWitoutPageObject.java

loginTestWithoutPageObject was added

---

TabelProj/pom.xml
TabelProj/src/test/java/loginTests/LoginTestWithOutPageObject.java

[QA] 26_07_2018 TabelA LoginTestWithOutPageObject was added

---

GnatiukProj/src/test/java/loginTests/LoginTestWithOutPageObject.java

Ubuntu comp

---

KushnirProj/pom.xml
KushnirProj/src/log4j.properties
KushnirProj/src/main/java/pages/HomePage.java
KushnirProj/src/main/java/pages/LoginPage.java
KushnirProj/src/main/java/pages/ParentPage.java
KushnirProj/src/test/java/loginTests/LoginTest.java
KushnirProj/src/test/java/parentTest/ParentTest.java

[QA] login test was added

---

TabelProj/pom.xml
TabelProj/src/log4j.properties
TabelProj/src/main/java/pages/HomePage.java
TabelProj/src/main/java/pages/LoginPage.java
TabelProj/src/main/java/pages/ParentPage.java
TabelProj/src/test/java/loginTests/LoginTest.java
TabelProj/src/test/java/loginTests/LoginTestWithOutPageObject.java
TabelProj/src/test/java/parentTest/ParentTest.java

BAG  loginTest  TabelA_17_07_New

---

overAll/pom.xml
overAll/src/log4j.properties
overAll/src/main/java/pages/HomePage.java
overAll/src/main/java/pages/LoginPage.java
overAll/src/main/java/pages/ParentPage.java
overAll/src/test/java/loginTests/LoginTest.java
overAll/src/test/java/parentTest/ParentTest.java

loginTest was added

---

PasternakProj/pom.xml
PasternakProj/src/main/java/pages/HomePage.java
PasternakProj/src/main/java/pages/LoginPage.java
PasternakProj/src/main/java/pages/ParentPage.java
PasternakProj/src/test/java/loginTests/LoginTest.java
PasternakProj/src/test/java/loginTests/LoginTestWhithoutPageObject.java
PasternakProj/src/test/java/parentTest/ParentTest.java

Login test was added

---

VoloschukProj/src/main/java/pages/LoginPage.java
VoloschukProj/src/test/java/loginTests/LoginTest.java

[QA] Invalid Login test was added

---

GnatiukProj/src/main/java/pages/HomePage.java
GnatiukProj/src/test/java/loginTests/LoginTest.java
GnatiukProj/src/test/java/parentTest/ParentTest.java

Invalid Login Test

---

TabelProj/src/Locator_V3.properties
TabelProj/src/main/java/pages/LoginPage.java
TabelProj/src/main/java/pages/ParentPage.java
TabelProj/src/test/java/loginTests/LoginTest.java

@tradulenko   HW UnValidLogIn   Tabel_A

[QA] 31_07_2018 Tabel_A HW UnValidLogIn

---

MatiushinProj/src/main/java/pages/LoginPage.java
MatiushinProj/src/test/java/loginTests/LoginPage.java

Matiushyn2607

---

KushnirProj/src/main/java/libs/ActionsWithOurElements.java
KushnirProj/src/main/java/pages/HomePage.java
KushnirProj/src/main/java/pages/LoginPage.java
KushnirProj/src/main/java/pages/ParentPage.java
KushnirProj/src/main/java/pages/SparesPage.java
KushnirProj/src/test/java/parentTest/ParentTest.java
KushnirProj/src/test/java/spares/AddNewSpare.java

[QA] add spare test

---

MatiushinProj/src/main/java/libs/ActionsWithElements.java
MatiushinProj/src/main/java/pages/HomePage.java
MatiushinProj/src/main/java/pages/LoginPage.java
MatiushinProj/src/main/java/pages/ParentPage.java
MatiushinProj/src/main/java/pages/SparesPage.java
MatiushinProj/src/test/java/loginTests/LoginTests.java
MatiushinProj/src/test/java/parentTest/ParentTest.java
MatiushinProj/src/test/java/spears/AddNewSpear.java

[qa] spears

---

TabelProj/src/main/java/libs/ActionWithOurElement.java
TabelProj/src/main/java/pages/HomePage.java
TabelProj/src/main/java/pages/LoginPage.java
TabelProj/src/main/java/pages/ParentPage.java
TabelProj/src/main/java/pages/SparesPage.java
TabelProj/src/test/java/parentTest/ParentTest.java
TabelProj/src/test/java/sparse/AddNewSpare.java

@tradulenko   ClassWork AddNewSpare impl

Tabel a 31 07 2018

---

AndrosovichProj/pom.xml
AndrosovichProj/src/main/java/libs/ActionsWithOurElements.java
AndrosovichProj/src/main/java/pages/HomePage.java
AndrosovichProj/src/main/java/pages/LoginPage.java
AndrosovichProj/src/main/java/pages/ParentPage.java
AndrosovichProj/src/main/java/pages/SparesPage.java
AndrosovichProj/src/test/java/loginTests/LoginTest.java
AndrosovichProj/src/test/java/loginTests/LoginTestWithOutPageObject.java
AndrosovichProj/src/test/java/mainPack/test
AndrosovichProj/src/test/java/parentTest/ParentTest.java
AndrosovichProj/src/test/java/spares/AddNewSpare.java

[QA] AddNewSpare impl

---

KushnirProj/src/main/java/libs/ActionsWithOurElements.java
KushnirProj/src/main/java/pages/EditSparePage.java
KushnirProj/src/main/java/pages/SparesPage.java
KushnirProj/src/test/java/parentTest/ParentTest.java
KushnirProj/src/test/java/spares/AddNewSpare.java

[QA] add Spare Page

---

PasternakProj/src/main/java/pages/HomePage.java
PasternakProj/src/test/java/loginTests/LoginTest.java
PasternakProj/src/test/java/loginTests/LoginTestWhithoutPageObject.java
PasternakProj/src/test/java/parentTest/ParentTest.java

@SeleniumQALight 
invalidLoginTest was added
dont know how to cancel the waiting of 15 sec from implicitlyWait before finishing test :(

Pasternak 03 08

---

VoloschukProj/src/main/java/libs/ActionsWithOurElements.java
VoloschukProj/src/main/java/pages/EditSparePage.java
VoloschukProj/src/main/java/pages/LoginPage.java
VoloschukProj/src/main/java/pages/SparesPage.java
VoloschukProj/src/test/java/parentTest/ParentTest.java
VoloschukProj/src/test/java/spares/AddNewSpare.java

Voloshchuk 0508

---

GnatiukProj/src/main/java/libs/ActionsWithOurElements.java
GnatiukProj/src/main/java/pages/EditSparePage.java
GnatiukProj/src/main/java/pages/SparePage.java
GnatiukProj/src/test/java/parentTest/ParentTest.java
GnatiukProj/src/test/java/spares/AddNewSpare.java

[QA] SparePage added

---

AndrosovichProj/src/main/java/libs/ActionsWithOurElements.java
AndrosovichProj/src/main/java/pages/EditSparePage.java
AndrosovichProj/src/main/java/pages/SparesPage.java
AndrosovichProj/src/test/java/parentTest/ParentTest.java
AndrosovichProj/src/test/java/spares/AddNewSpare.java

Androsovich 08 02

---

AndrosovichProj/src/main/java/pages/EditSparePage.java
AndrosovichProj/src/test/java/spares/AddNewSpare.java

[QA] selectSpareTypeByClick

---

AndrosovichProj/src/main/java/libs/ActionsWithOurElements.java
AndrosovichProj/src/test/java/loginTests/UnValidLoginWithParams.java
AndrosovichProj/src/test/java/parentTest/ParentTest.java

[QA] Wait was added

---

PetrovskaiaProj/src/main/java/libs/ActionsWithOurElements.java
PetrovskaiaProj/src/main/java/pages/EditSparePage.java
PetrovskaiaProj/src/main/java/pages/ParentPage.java
PetrovskaiaProj/src/main/java/pages/SparesPage.java
PetrovskaiaProj/src/test/java/loginTests/UnValidLoginWithParams.java
PetrovskaiaProj/src/test/java/loginTests/loginTest.java
PetrovskaiaProj/src/test/java/parenttest/Parenttest.java

WaitWasAdded

---

BychovyiProj/src/main/java/libs/ActionsWithOurElements.java
BychovyiProj/src/test/java/loginTests/UnValidLoginWithParams.java
BychovyiProj/src/test/java/parentTest/ParentTest.java

[QA] new test 07.08.2018

---

PetrovskaiaProj/pom.xml
PetrovskaiaProj/src/main/java/libs/ActionsWithOurElements.java
PetrovskaiaProj/src/main/java/libs/ConfigProperties.java
PetrovskaiaProj/src/main/java/libs/ConfigProperties.properties
PetrovskaiaProj/src/main/java/libs/Utils.java
PetrovskaiaProj/src/main/java/pages/ParentPage.java
PetrovskaiaProj/src/test/java/loginTests/loginTest.java
PetrovskaiaProj/src/test/java/parenttest/Parenttest.java

ClassWorkWithProperties

---

PasternakProj/pom.xml
PasternakProj/src/main/java/libs/ConfigData.java
PasternakProj/src/main/java/libs/Database.java
PasternakProj/src/main/java/libs/UtilsForDB.java
PasternakProj/src/test/java/testDB/TestDataBase.java

Pasternak 16 08

---

VoloschukProj/pom.xml
VoloschukProj/src/main/java/libs/ActionsWithOurElements.java
VoloschukProj/src/main/java/libs/ConfigData.java
VoloschukProj/src/main/java/libs/Database.java
VoloschukProj/src/main/java/libs/UtilsForDB.java
VoloschukProj/src/test/java/testDB/TestDatabase.java

Voloshchuk-1608

---

.gitignore
MatiushinProj/src/main/java/pages/SparesPage.java
PasternakProj/pom.xml
PasternakProj/src/main/java/libs/CurrencyValues.java
PasternakProj/src/main/java/libs/ResponseStructureForRestAssuredTest.java
PasternakProj/src/main/java/pages/LoginPage.java
PasternakProj/src/main/java/restSteps/MainRestSteps.java
PasternakProj/src/test/java/loginTests/LoginTest.java
PasternakProj/src/test/java/parentTest/ParentTest.java
PasternakProj/src/test/java/restTest/RestAssuredTest.java
PasternakProj/src/test/java/restTest/TestRestAssured.java
PasternakProj/src/test/java/restTest/linksForRestAssured

Pasternak 21 08

---

KushnirProj/src/test/java/suites/LoginSuite.java

[QA] 23/08
